name: Unit Tests for frontend

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  Jest:
    name: Jest Unit tests for dev branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Run Tests
        run: |
          npm install --legacy-peer-deps
          npm run test
